### ISSUE TITLE
Criar uma função para preencher os modelos `ScholaryArticles`, `Contributors`, `Affiliations`

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#10]
### Descrição da tarefa
Criar uma função para preencher os modelos `ScholaryArticles`, `Contributors`, `Affiliations`

O parâmetro de entrada é o conteúdo é `RawUnpaywall.jsonl`

**Comment by Rossi-Luciano** [comment]
Os scripts foram criados e estão disponíveis para avaliação no PR #7.
