### ISSUE TITLE
Criar um modelo que contenha affiliation e todos os autores associados

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#11]
### Descrição da tarefa
Criar um modelo que contenha affiliation e todos os autores associados
Objetivo: a partir de um registro de affiliation chegar a todos os autores relacionados

Verificar a questão de fazer um modelo que associe autor + ano (ano de publicação do artigo vai dar o ano em que o autor se encontra afiliado) + instituição

**Comment by Rossi-Luciano** [comment]
Este item ficou pendente de avaliação sobre a versatilidade dos atributos `many-to-many`.
