### ISSUE TITLE
Criar uma função para selecionar os registros de `RawUnpaywall` para serem processados

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#12]
### Descrição da tarefa
Criar uma função para selecionar os registros de `RawUnpaywall` para serem processados

Como nem todos os registros são do interesse, precisamos de uma função que filtre o conteúdo coletado.
Os parâmetros desta função devem ser `year` e `genre`.

Nota: Os registros cujo campo `is_paratext == true` pode ser descartado.

**Comment by Rossi-Luciano** [comment]
Foi feita.
