### ISSUE TITLE
Realizar nova coleta de dados do Unpaywall

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#162]
Link para obter um snapshot da base de dados: 

https://docs.google.com/forms/d/e/1FAIpQLSfP9MLUosBU8C_pglqunbSrRpQADlRoNp5HzJZfNAM49EEy6g/viewform

**Comment by gitnnolabs** [comment]
@robertatakenaka 

Solicitando novamente um snapshot para o unpaywall, verifiquei que estamos com a versão mais recente: 

Veja: 
![Screenshot 2023-03-28 at 09 20 38](https://user-images.githubusercontent.com/86991526/228234275-c5d5c07f-2216-43d4-be86-d7c6499b48b5.png)

Versão que temos no servidor: 

![Screenshot 2023-03-28 at 09 21 45](https://user-images.githubusercontent.com/86991526/228234390-f2e2390f-ca3b-4f07-a2df-264a6e2538c2.png)
