### ISSUE TITLE
Realizar stress test / identificar pontos de lentidão

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#163]

**Comment by gitnnolabs** [comment]
Em avaliação com o @rondinelisaad verificamos em conjunto e realizamos ajuste que garante uma resposta aceitável do tempo de execução da aplicação. 

Também ficou acordado que no momento de lentidão devemos verificar em conjunto.

**Comment by gitnnolabs** [comment]
Atualmente estamos com um tempo de resposta baixo veja: 

![Screenshot 2023-03-22 at 09 26 00](https://user-images.githubusercontent.com/86991526/226905741-5ed6074a-009d-4709-bbe0-486f0f35184a.png)
