### ISSUE TITLE
Incluir novos campos nos formulários dos diretórios

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#19]
### Descrição da tarefa

Incluir novos campos nos formulários dos diretórios.

**Áreas temáticas**
Repetitivos. Usar em Português.

Nível 0 - Colégios Temáticos
https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao
- Ciências da Vida
- Ciências Físicas, Tecnológicas e Multidisciplinares
- Humanidades

Nível 1 - Grandes áreas da CAPES
https://www.scielo.br/journals/thematic?status=current

Nível 2 - Área de avaliação CAPES
(aguardando info)

**Palavras-chaves**
Repetitivo

**Prática** (são as colunas da matriz / objetos e processos de comunicação de pesquisa)

Lista de opções:
- 100: menção genérica à CA ou todas as práticas  
- 210: preprints
- 220: version of record indexados - periódicos, documentos, artigos, ....
- 230: livros, capítulo de livros
- 240: teses, dissertações, TCC
- 250: projetos de pesquisa
- 260: declarações
- 270: outros docs
- 280: repositórios tipo verde – documentos em geral, ..
- 300: dados genéricos
- 310: códigos 
- 400: peer review
- 500: ciência cidadã
- 600: recursos educacionais
- 900: outra

**Ação**
No nível sistema, as opções são:

- 10: política, recomendação etc.
- 20: desempenho
- 30: infraestrutura
- 40: educação
- 50: divulgação
- 90: outras

No formulário de cada diretório o campo fica com o valor padrão correspondente. Isso ajuda em exportação de dados, API, cruzamento dos dados. (Análogo a ter como valor padrão o país BR)

**Comment by ednilson** [comment]
@robertatakenaka 
Notei que de acordo com o documento da CAPES a descrição **correta** é.
"Ciências Exatas, Tecnológicas e Multidisciplinar" 
e não 
"Ciências Físicas, Tecnológicas e Multidisciplinares". 

https://www.gov.br/capes/pt-br/acesso-a-informacao/acoes-e-programas/avaliacao/sobre-a-avaliacao/areas-avaliacao/sobre-as-areas-de-avaliacao

**Comment by ednilson** [comment]
Será resolvido no issue #42
