### ISSUE TITLE
Carregar a lista de estados do Brasil associada a sua região

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#36]
### Descrição da tarefa
Descreva de forma clara e objetiva a tarefa em questão

https://docs.google.com/spreadsheets/d/17BO-ueuDWhDeHTP6Fx99SvJtOdPXG0jxYkQvFoGTIdY/edit#gid=536161510

**Comment by gitnnolabs** [comment]
Realizando...
