### ISSUE TITLE
Criar um modelo `RawUnpaywall` para guardar registro da coleta

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#9]
### Descrição da tarefa
Criar um modelo `RawUnpaywall` para guardar registro da coleta.
Os objetivos desta tarefa são:
- identificar os dados já coletados, usando doi e updated
- identificar os registros de interesse para o projeto, usando year e `is_paratext != true`

O modelo deve ter os seguintes campos
- doi
- harvesting_creation (data de ingresso dos dados de coleta no sistema)
- is_paratext (em caso de ser igual a true, preencher apenas `doi`, `is_paratext`, `updated`, `harvesting_creation`) | https://support.unpaywall.org/support/solutions/articles/44001894783-what-does-is-paratext-mean-in-the-api-
- year
- genre
- updated
- jsonl

**Comment by Rossi-Luciano** [comment]
O modelo foi contruído.
Conforme conversamos, os dados serão completamente considerados em RawUnpaywall.
