### ISSUE TITLE
Na interface do Search não está apresentando todos os dados do registro dos diretórios

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#93]
### Descrição da tarefa
Na interface do Search não está apresentando todos os dados do registro dos diretórios

Por exemplo, em todos os diretórios há instituições relacionadas, seja como organizadora, seja como instituição responsável. Como não há uma página para visualizar os detalhes dos registros, estes dados tem que ser apresentados no resultado da busca.

Apresentar pelo menos, os dados:
- institutições ou organization
- áreas temáticas
- classification

**Comment by gitnnolabs** [comment]
Ajustando...
