### ISSUE TITLE
Apresenta IndexError ao clicar em filtro que tem vírgula (concatenação de dois itens)

### ISSUE THREAD

**Issue by robertatakenaka** [scieloorg/scms-oca#94]
### Descrição do problema
Apresenta IndexError ao clicar em filtro que tem vírgula (concatenação de dois itens)

### Passos para reproduzir o problema
1. Acesse a página `/search`
2. Clique em algum filtro que tenha mais de um item, separados por vírgula
<img width="258" alt="Captura de Tela 2022-10-22 às 15 31 34" src="https://user-images.githubusercontent.com/505143/197357129-a487116f-4922-4a8f-9e46-04fe50ac26cc.png">

3. Observe o erro apresentado
<img width="1440" alt="Captura de Tela 2022-10-22 às 15 28 46" src="https://user-images.githubusercontent.com/505143/197357091-6573b857-b823-4ce1-b120-4d8f091e9ce2.png">

### Comportamento esperado
Manter na mesma página, e visualizar os resultados do filtro selecionado

### Screenshots ou vídeos
n/a

### Anexos
n/a

### Ambiente utilizado
LOCAL

**Comment by gitnnolabs** [comment]
Ajustando...
